// types/profileMessages.ts

export const profileMessages: Record<string, string> = {
    Aventurero: "¡Felicidades, Espíritu Libre y Audaz!. Tu sed de nuevas experiencias y tu valentía para explorar lo desconocido te colocan en un camino lleno de emociones, experiencias y autodescubrimiento. Eres el pionero que no teme adentrarse en lo inexplorado, el que encuentra la belleza en el riesgo y la aventura en cada esquina. El mundo es tu vasto patio de juegos, y cada día es una oportunidad para sumergirte en nuevas aventuras. ¡Sigue tu corazón intrépido, pues grandes historias te esperan!",

    Guardian: "¡Saludos, Protector del Planeta!. Tu compromiso con la preservación de nuestro mundo y tu profunda conexión con la naturaleza te convierten en una fuerza vital para el cambio positivo. Eres la voz de los que no tienen voz, el cuidador de la Tierra que busca armonía y equilibrio. Tu pasión inspira a otros a tomar acción y a valorar las maravillas de nuestro entorno natural. ¡Juntos, podemos hacer una diferencia significativa!",

    Sabio: "¡Bienvenido, Eterno Buscador del Conocimiento!. Tu curiosidad insaciable y amor por el aprendizaje te guían a través de la vida. Tu mente analítica y tu deseo de entender los misterios del universo te hacen un pensador profundo y un solucionador de problemas nato. Ya sea explorando antiguas filosofías o innovaciones modernas, tu búsqueda del conocimiento es interminable. Eres el faro de sabiduría en un mundo sediento de entendimiento. ¡Que tu viaje a través del vasto océano del conocimiento sea fructífero y revelador!",

    Conector: "¡Saludos, Arquitecto de Puentes y Amistades!. Tu habilidad natural para relacionarte con los demás y crear redes de apoyo es incomparable. Eres el tejedor de comunidades, el creador de vínculos, la persona que reúne a los demás con calidez y empatía. Tu presencia ilumina las habitaciones y tu energía positiva une a las personas. En un mundo que a veces parece dividido, tu capacidad para construir puentes es más importante que nunca. ¡Continúa reuniendo a las personas, pues tu impacto colectivo tiene el poder de transformar el mundo!",

    Creador: "¡Bravo, Alma Creativa!. Tu imaginación es tu brújula, guiándote a crear belleza y significado en todas sus formas. Artista, escritor, músico, diseñador: sea cual sea tu medio, lo usas para explorar las profundidades de la experiencia humana y compartir tu visión única con el mundo. Eres un recordatorio viviente de que, a través de la creatividad, podemos explorar nuevas perspectivas y transformar lo ordinario en extraordinario. ¡Que tu viaje creativo siga siendo audaz, brillante y profundamente satisfactorio!",

    Visionario: "¡Enhorabuena, Pionero del Futuro!. Siempre mirando hacia adelante, soñando con posibilidades ilimitadas y liderando el camino hacia un mañana mejor. Tu mente está llena de ideas innovadoras que tienen el potencial de revolucionar la forma en que vivimos, trabajamos y nos relacionamos entre nosotros y con nuestro planeta. Con tu combinación única de imaginación, ingenio y perspicacia, estás preparado para enfrentar los desafíos del futuro y convertir tus visiones en realidades tangibles. Eres un faro de inspiración, motivando a otros a expandir sus horizontes y a soñar en grande. ¡Sigue adelante con tu creatividad sin límites, pues tu visión del futuro tiene el poder de transformar el mundo para mejor!",
    
    Guerrero: "¡Saludamos tu espíritu indomable!. Tu valentía y determinación te impulsan a enfrentar los desafíos más extremos y peligrosos. Tu fuerza y coraje inspiran a otros, y tu pasión por la acción y el movimiento te convierten en un líder nato en cualquier aventura. Ya sea escalando montañas, surfeando olas gigantes o enfrentando cualquier otro desafío, tu determinación nunca flaquea. ¡Sigue adelante con tu espíritu audaz y valiente, pues cada batalla que enfrentas te fortalece aún más!"
  };
  